# -*- coding: utf-8 -*-
"""Assignment 1 Software Modelling - UML Use Case and UML Class diagrams

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sAe9g4vjKbZwAmtJaWvsgwkrbtcSXoM0
"""

from datetime import datetime


class Passenger:
    def __init__(self, first_name, last_name, frequent_flyer_number, passport_number, email):
        self._first_name = first_name
        self._last_name = last_name
        self._frequent_flyer_number = frequent_flyer_number
        self._passport_number = passport_number
        self._email = email

    def get_first_name(self):
        return self._first_name

    def set_first_name(self, first_name):
        self._first_name = first_name

    def get_last_name(self):
        return self._last_name

    def set_last_name(self, last_name):
        self._last_name = last_name

    def get_frequent_flyer_number(self):
        return self._frequent_flyer_number

    def set_frequent_flyer_number(self, frequent_flyer_number):
        self._frequent_flyer_number = frequent_flyer_number

    def get_passport_number(self):
        return self._passport_number

    def set_passport_number(self, passport_number):
        self._passport_number = passport_number

    def get_email(self):
        return self._email

    def set_email(self, email):
        self._email = email

    def get_full_name(self):
        return f"{self._first_name} {self._last_name}"


class Flight:
    def __init__(self, flight_number, departure_airport, arrival_airport, departure_time, arrival_time):
        self._flight_number = flight_number
        self._departure_airport = departure_airport
        self._arrival_airport = arrival_airport
        self._departure_time = departure_time
        self._arrival_time = arrival_time

    def get_flight_number(self):
        return self._flight_number

    def set_flight_number(self, flight_number):
        self._flight_number = flight_number

    def get_departure_airport(self):
        return self._departure_airport

    def set_departure_airport(self, departure_airport):
        self._departure_airport = departure_airport

    def get_arrival_airport(self):
        return self._arrival_airport

    def set_arrival_airport(self, arrival_airport):
        self._arrival_airport = arrival_airport

    def get_departure_time(self):
        return self._departure_time

    def set_departure_time(self, departure_time):
        self._departure_time = departure_time

    def get_arrival_time(self):
        return self._arrival_time

    def set_arrival_time(self, arrival_time):
        self._arrival_time = arrival_time

    def get_flight_details(self):
        return f"Flight Number: {self._flight_number}, From: {self._departure_airport}, To: {self._arrival_airport}"

    def get_departure_info(self):
        return f"Departure: {self._departure_time.strftime('%Y-%m-%d %H:%M')} from {self._departure_airport}"

    def get_arrival_info(self):
        return f"Arrival: {self._arrival_time.strftime('%Y-%m-%d %H:%M')} at {self._arrival_airport}"


class BoardingPass:
    def __init__(self, passenger, flight, seat_number, boarding_time, gate_number):
        self._boarding_pass_id = f"{passenger.get_passport_number()}-{flight.get_flight_number()}"
        self._seat_number = seat_number
        self._boarding_time = boarding_time
        self._gate_number = gate_number
        self._barcode = "1234567890"  # Placeholder barcode

    def get_boarding_pass_id(self):
        return self._boarding_pass_id

    def get_seat_number(self):
        return self._seat_number

    def set_seat_number(self, seat_number):
        self._seat_number = seat_number

    def get_boarding_time(self):
        return self._boarding_time

    def set_boarding_time(self, boarding_time):
        self._boarding_time = boarding_time

    def get_gate_number(self):
        return self._gate_number

    def set_gate_number(self, gate_number):
        self._gate_number = gate_number

    def get_barcode(self):
        return self._barcode

    def set_barcode(self, barcode):
        self._barcode = barcode

    def generate_barcode(self):
        # Placeholder for barcode generation logic
        pass

    def get_seat_info(self):
        return f"Seat Number: {self._seat_number}"

    def print_boarding_pass(self):
        # This method will compile the boarding pass details into a printable format
        pass


class CheckInCounter:
    def __init__(self, counter_number, agent_name, open_time, close_time, status):
        self._counter_number = counter_number
        self._agent_name = agent_name
        self._open_time = open_time
        self._close_time = close_time
        self._status = status

    def get_counter_number(self):
        return self._counter_number

    def set_counter_number(self, counter_number):
        self._counter_number = counter_number

    def get_agent_name(self):
        return self._agent_name

    def set_agent_name(self, agent_name):
        self._agent_name = agent_name

    def get_open_time(self):
        return self._open_time

    def set_open_time(self, open_time):
        self._open_time = open_time

    def get_close_time(self):
        return self._close_time

    def set_close_time(self, close_time):
        self._close_time = close_time

    def get_status(self):
        return self._status

    def set_status(self, status):
        self._status = status

    def check_in_passenger(self, passenger):
        # Placeholder for check-in logic. Should return a BoardingPass object.
        pass

# Create instances using the classes defined above
# Assuming placeholder times for demonstration purposes
departure_time = datetime(2024, 2, 23, 15, 30)
arrival_time = datetime(2024, 2, 23, 17, 45)
boarding_time = datetime(2024, 2, 23, 10, 0)
open_time = datetime(2024, 2, 23, 10, 0)
close_time = datetime(2024, 2, 23, 15, 0)

# Creating instances of the classes
passenger = Passenger("Khalifa", "Alshehhi", "FF123", "P1234567", "Khalifa@GOAT.com")
flight = Flight("NA1234", "Dubai", "France", departure_time, arrival_time)
boarding_pass = BoardingPass(passenger, flight, "1A", boarding_time, "G10")
check_in_counter = CheckInCounter(3, "Alice", open_time, close_time, "Open")

# Using the object’s functions to populate and display all the boarding pass details
# Note: The logic for printing the boarding pass would need to be completed as per the requirements
boarding_pass_details = f"""
Boarding Pass ID: {boarding_pass._boarding_pass_id}
Passenger: {passenger.get_full_name()}
Flight: {flight.get_flight_details()}
Seat: {boarding_pass.get_seat_info()}
Gate: {boarding_pass._gate_number}
Boarding Time: {boarding_pass.get_boarding_time().strftime('%Y-%m-%d %H:%M')}
Barcode: {boarding_pass._barcode}
"""

print(boarding_pass_details)