# -*- coding: utf-8 -*-
"""Question 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Or5e24DwgEJzzZ1AI8vocUVxW4GajaF
"""

class Chocolate:
    def __init__(self, weight, price, type_chocolate, id_chocolate):
        self.weight = weight
        self.price = price
        self.type = type_chocolate
        self.id = id_chocolate

    def __repr__(self):
        return (f"Chocolate(weight={self.weight} gm, price={self.price} AED, "
                f"type={self.type}, id={self.id})")

class Student:
    def __init__(self, name):
        self.name = name
        self.chocolate = None

    def __repr__(self):
        return f"Student(name={self.name}, chocolate={self.chocolate})"

def find_student_with_chocolate(students, target, by_weight=True):
    left, right = 0, len(students) - 1
    while left <= right:
        mid = (left + right) // 2
        chocolate_attr = students[mid].chocolate.weight if by_weight else students[mid].chocolate.price
        if chocolate_attr == target:
            return mid
        elif chocolate_attr < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1  # Target not found

# Creating students with real names and assigning chocolates
students_with_chocolates = [
    Student("Khalifa"),
    Student("Messi"),
    Student("Aziz")
]
students_with_chocolates[0].chocolate = Chocolate(5, 2, 'Almond', '002')
students_with_chocolates[1].chocolate = Chocolate(6, 3, 'Hazelnut', '004')
students_with_chocolates[2].chocolate = Chocolate(7, 4, 'Peanut Butter', '005')

# Test cases with real names
index_by_weight = find_student_with_chocolate(students_with_chocolates, 6, by_weight=True)
index_by_price = find_student_with_chocolate(students_with_chocolates, 4, by_weight=False)

# Displaying results
if index_by_weight != -1:
    print(f"Index by Weight: {index_by_weight}, Student: {students_with_chocolates[index_by_weight]}")
else:
    print("No student found with the specified chocolate weight.")

if index_by_price != -1:
    print(f"Index by Price: {index_by_price}, Student: {students_with_chocolates[index_by_price]}")
else:
    print("No student found with the specified chocolate price.")